Squashed 'tracker/' changes from 802b648..dd87c6f
dd87c6f Release 1.0.1
be78e89 libtracker-miner: Pass parent flags when reindexing a previously ignored folder
3162885 libtracker-miner: Pass flags explicitly when creating crawling root data
7dc4366 libtracker-miner: Call check_directory() on root dir to crawl
8edf06b libtracker-miner: Fallback to URN querying on UPDATE events and API requests
67fd48a libtracker-miner: Perform leveled notification in TrackerFileNotifier
d836f00 libtracker-miner: Store iri transiently as GFile qdata
971d0f4 libtracker-miner: Add tracker_file_system_get_file_type()
32904b7 libtracker-miner: Make crawler take a maximum recursion depth
983e701 tracker-extract: MP3s with ID3v23 tags should not hit infinite loop
064d325 tracker-miner-rss: Fixed subclassing from TrackerMinerOnline
f2ca2df [l10n] Update Catalan translation
ea3b8f3 Updated Indonesian translation
9f9c368 Updated German translation
2ef540e Updated Lithuanian translation
1f4f1ef Updated Polish translation
a4d48e0 Updated Galician translations
5a87167 Updated Brazilian Portuguese translation
660b5a3 tracker-search: Fix output for email searching
1e88898 Updated Ukrainian translation
ad32060 libtracker-miner: Decorator causes crash on _update_array_finish() failures.
c20c1dc Make sure vorbis extractor builds without libmediaart
c5e9204 build: Add SQLite version warning for 3.8.4.2
ff835ab doap: update URLs
caa0ff3 Fix handling when no match is found by libicu charset detector
bb5c854 Make it possible to disable libicu and libenca based charset detectors
ecca335 giflib 4.2.x doesn't have PrintGifError
854f5fd tracker-tag: Replace --or-operator with --and-operator for --list option
d2683f8 Updated Indonesian translation
1db0df4 Updated German translation
310385f Updated Ukrainian translation
02232ee Updated Greek translation
2038d0e Updated Russian translation
270d420 Updated Ukrainian translation
a2895d7 Updated Russian translation
febda3a Added Basque language\nAdded 'eu' (Basque) to LINGUAS
f008c16 Updated Korean translation
634543f update zh_CN translation
2b3e81c Release 1.0.0
4bd4b1e libtracker-sparql: Make sure we check the env before choosing the bus type
26cf4a0 Updated Portuguese translation
a01c4ea Updated Danish translation
6fda3da Updated Traditional Chinese translation(Hong Kong and Taiwan)
b89aa75 Merge branch 'make-decorator-errors-public'
a000245 Release 0.17.8
9244007 Revert "libtracker-sparql: Fix undefined reference to symbol 'tracker_ipc_bus'"
4d2f98c Updated Hungarian translation
9f68be3 docs: minor tracker-store man page cleanup
67e1ee2 build: Fix warning for --with-compile-warnings, which mentions --enable-compile-warnings
9dfde8d libtracker-miner, tracker-extract: Don't g_warning() on decorator items we don't process
1d62aaa Updated Indonesian translation
963e53e libtracker-sparql: Don't use internal tracker_ipc_bus() function in examples/
3898355 Updated Latvian translation
7822e2d Updated Danish translation
0e6e0a8 Updated Latvian translation
c3e383a Updated Czech translation
0fc4afd tracker-extract: Fixed broken ontology use for JPEGS, dc:indentifier -> dc:identifier
476f349 Release 0.17.7
4623bcd libtracker-sparql: Fix undefined reference to symbol 'tracker_ipc_bus'
6aea628 Updated Italian translation
66c85b3 Updated Serbian translation

git-subtree-dir: tracker
git-subtree-split: dd87c6fbee8cd8ca775984521bfc2c816b178731